'use client';
import {useEffect,useRef,useState} from 'react';
import {getClient,authHeaders,driveToken} from '@/lib/config';
import {chooseDirectory,listRecordings,preference,setPreference,retryUploads,recordingBlob,downloadBlob,removeCachedVideo,syncMetadata,type Recording} from '@/lib/storage';
import type {User} from '@supabase/supabase-js';
import SetupGuide from './setup-guide';
function ToolIcon({name}:{name:'videos'|'statistics'|'settings'|'refresh'|'reset'}){const paths={reset:'M3 12a9 9 0 1 0 3-6.7M3 3v6h6',videos:'M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z',statistics:'M18 20V10M12 20V4M6 20v-6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',refresh:'M23 4v6h-6M20.49 15a9 9 0 1 1-2.12-9.36L23 10'};return <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]}/></svg>;}
export default function Workspace(){
  const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[panel,setPanel]=useState(false),[records,setRecords]=useState<Recording[]>([]),[notice,setNotice]=useState(''),[directory,setDirectory]=useState(''),[driveEmail,setDriveEmail]=useState(''),[autoDrive,setAutoDrive]=useState(false),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false);
  const frame=useRef<HTMLIFrameElement>(null);
  const [studioReady,setStudioReady]=useState(false),[query,setQuery]=useState(''),[sessionChanged,setSessionChanged]=useState(false);
  function command(command:string,query?:string){frame.current?.contentWindow?.postMessage({type:'cam-command',command,query},location.origin);}
  async function refresh(){const rows=await listRecordings();setRecords(rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setDirectory((await preference<{name:string}|null>('directory',null))?.name||'');setAutoDrive(await preference('autoDrive',false));}
  useEffect(()=>{let unsub:(()=>void)|undefined;void(async()=>{try{const client=await getClient();if(client){setUser((await client.auth.getSession()).data.session?.user||null);const {data}=client.auth.onAuthStateChange((_event,current)=>{setUser(current?.user||null);void refresh();});unsub=()=>data.subscription.unsubscribe();}await refresh();try{setDriveEmail((await driveToken()).email);}catch{}const drive=new URL(location.href).searchParams.get('drive');if(drive){setNotice(drive==='connected'?'Đã kết nối Google Drive.':drive==='cancelled'?'Đã hủy kết nối Drive.':'Kết nối Drive chưa thành công. Hãy thử lại.');history.replaceState(null,'','/');}}catch(error){setNotice(error instanceof Error?error.message:'Chưa tải được cấu hình.');}finally{setReady(true);}})();
    const onChange=()=>void refresh();window.addEventListener('cam-recordings-changed',onChange);
    const onMessage=(event:MessageEvent)=>{if(event.origin!==location.origin||event.source!==frame.current?.contentWindow)return;if(event.data?.type==='cam-ready')setStudioReady(true);if(event.data?.type==='cam-state')setRecording(!!event.data.recording);if(event.data?.type==='cam-session-changed'){setSessionChanged(true);setNotice('Tài khoản đã thay đổi. Dừng quay rồi tải lại ứng dụng.');}};window.addEventListener('message',onMessage);
    const timer=setInterval(onChange,4000);return()=>{unsub?.();clearInterval(timer);window.removeEventListener('cam-recordings-changed',onChange);window.removeEventListener('message',onMessage);};
  },[]); // Camera surface is mounted once and is not rerendered per video frame.
  useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(recording){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[recording]);
  async function action(fn:()=>Promise<unknown>){setBusy(true);setNotice('');try{await fn();await refresh();}catch(error){setNotice(error instanceof Error?error.message:'Thao tác chưa thành công.');}finally{setBusy(false);}}
  async function login(){const client=await getClient();if(!client)throw new Error('Tài khoản chưa được cấu hình.');const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/auth/callback`}});if(error)throw error;}
  async function connect(){const response=await fetch('/api/drive/connect',{method:'POST',headers:await authHeaders()});const data=await response.json();if(!response.ok)throw new Error(data.error);location.assign(data.url);}
  const pending=records.filter(row=>['queued','uploading','error'].includes(row.uploadStatus)).length;
  return <main className="workspace">
    <header className="cloudbar"><a className="brand" href="/"><span className="brand-icon">◉</span><span>CamDongHang<small><i className={recording?'recording-dot':'local-dot'}/>{recording?'ĐANG QUAY':'QUAY ĐÓNG HÀNG · TẠI MÁY'}</small></span></a>
      <nav className="cloud-actions" aria-label="Công cụ camera"><form className="quick-search" role="search" onSubmit={event=>{event.preventDefault();if(query.trim()){command('search',query.trim());setQuery('');}}}><span aria-hidden="true">⌕</span><input aria-label="Tìm nhanh vận đơn" placeholder="Tìm nhanh vận đơn…" value={query} onChange={event=>setQuery(event.target.value)} disabled={!studioReady}/></form>
        <div className="camera-tools">{(['videos','statistics','settings','refresh','reset'] as const).map(name=><button key={name} disabled={!studioReady} onClick={()=>command(name)}><ToolIcon name={name}/>{{videos:'Videos',statistics:'Thống kê',settings:'Cài đặt',refresh:'Refresh',reset:'Reset bố cục'}[name]}</button>)}</div>
        <SetupGuide recording={recording} onAction={action=>{if(action==='storage'){setPanel(true);void refresh();}else command(action);}}/>
        <button className="storage-button" title={`${directory?'Thư mục: '+directory:'Lưu tại máy'} · ${driveEmail?'Drive: '+driveEmail:'Chưa kết nối Drive'} · ${pending} video chờ tải`} onClick={()=>{setPanel(true);void refresh();}}>Lưu trữ{driveEmail&&<span className="drive-dot" aria-label="Đã kết nối Drive"/>}{pending>0&&<b>{pending}</b>}</button>{user?<button className="account-button" disabled={recording||busy} onClick={()=>setPanel(true)}>{user.user_metadata.full_name||user.email}</button>:<button className="primary account-button" disabled={!ready||recording||busy} onClick={()=>void action(login)}>Đăng nhập Google</button>}
      </nav></header>
    {notice&&<div className="notice" role="status">{notice}{sessionChanged&&<button disabled={recording} onClick={()=>location.reload()}>Tải lại ứng dụng</button>}<button aria-label="Đóng thông báo" onClick={()=>setNotice('')}>×</button></div>}
    {ready?<iframe ref={frame} title="Camera đóng hàng" className="studio" src="/studio/index.html" allow="camera; microphone; autoplay; fullscreen"/>:<div className="loading">Đang chuẩn bị camera…</div>}
    <footer className="app-footer"><span>Quay video đóng hàng và đọc QR/mã vạch trên máy bạn.</span><span><a href="/privacy" target="_blank">Quyền riêng tư</a> · <a href="/terms" target="_blank">Điều khoản</a></span></footer>
    {panel&&<div className="backdrop" onClick={()=>setPanel(false)}><aside className="drawer" role="dialog" aria-modal="true" aria-label="Lưu trữ và tài khoản" onClick={event=>event.stopPropagation()}><div className="drawer-head"><div><small>CAMDONGHANG</small><h2>Lưu trữ & tài khoản</h2></div><button aria-label="Đóng lưu trữ" onClick={()=>setPanel(false)}>×</button></div>
      <section><h3>Lưu video tại máy</h3><p>Chọn thư mục một lần để tự lưu mỗi khi kết thúc vận đơn. Bản dự phòng được giữ trong trình duyệt.</p><button disabled={busy} onClick={()=>void action(async()=>{setDirectory(await chooseDirectory());setNotice('Đã chọn thư mục lưu video.');})}>Chọn thư mục lưu</button>{directory&&<p className="success">✓ {directory}</p>}<p className="hint">Nếu chưa chọn thư mục, ứng dụng tải file xuống. Trình duyệt có thể yêu cầu cho phép tải nhiều file. Không xóa dữ liệu trình duyệt khi còn video chưa lưu.</p></section>
      <section><h3>Google Drive của bạn</h3>{user?<><p>{driveEmail||'Kết nối để tải video trực tiếp lên Drive của bạn.'}</p><div className="row"><button disabled={busy||recording} onClick={()=>void action(connect)}>{driveEmail?'Kết nối lại':'Kết nối Google Drive'}</button>{driveEmail&&<button disabled={busy||recording} onClick={()=>void action(async()=>{const response=await fetch('/api/drive/disconnect',{method:'POST',headers:await authHeaders()});if(!response.ok)throw new Error('Chưa ngắt được Drive.');setDriveEmail('');await setPreference('autoDrive',false);setAutoDrive(false);})}>Ngắt kết nối</button>}</div><label className="check"><input type="checkbox" checked={autoDrive} disabled={!driveEmail} onChange={event=>{setAutoDrive(event.target.checked);void setPreference('autoDrive',event.target.checked);}}/> Tự tải video mới lên Drive</label><button disabled={busy||!driveEmail} onClick={()=>void action(retryUploads)}>Thử lại video chờ tải</button></>:<><p>Đăng nhập để đồng bộ cài đặt và kết nối Drive. Bạn vẫn có thể quay, lưu tại máy khi chưa đăng nhập.</p><button disabled={busy||recording} className="primary" onClick={()=>void action(login)}>Đăng nhập Google</button></>}</section>
      <section><h3>Video trên trình duyệt này <span className="count">{records.length}</span></h3>{records.length===0?<p>Chưa có video. Bắt đầu bằng camera bên cạnh.</p>:records.slice(0,100).map(row=><article className="record" key={row.id}><div><strong>{row.code}</strong><small>{row.filename}</small><small>{new Date(row.createdAt).toLocaleString('vi-VN')} · {(row.size/1048576).toFixed(1)} MB · {row.duration}s</small><span className={row.uploadStatus==='uploaded'?'success':'hint'}>{row.uploadStatus==='uploaded'?'✓ Đã lưu Drive':row.uploadStatus==='uploading'?'Đang tải Drive…':row.uploadStatus==='error'?'Chờ thử lại':row.uploadStatus==='queued'?'Chờ tải Drive':row.localSaved?'✓ Đã lưu vào thư mục':'Bản dự phòng tại trình duyệt'}</span>{row.error&&<small className="error">{row.error}</small>}</div><div className="row"><button onClick={()=>void action(async()=>downloadBlob(await recordingBlob(row),row.filename))}>Tải xuống</button>{row.driveUrl&&<a className="button" href={row.driveUrl} target="_blank" rel="noopener noreferrer">Mở Drive</a>}{driveEmail&&!row.driveId&&<button onClick={()=>void action(async()=>{row.uploadStatus='queued';await(await import('@/lib/storage')).updateRecording(row);await retryUploads();})}>Tải Drive</button>}{row.blob&&(row.localSaved||row.driveId)&&<button onClick={()=>void action(()=>removeCachedVideo(row))}>Giải phóng bản dự phòng</button>}</div></article>)}</section>
      {user&&<section><p>{user.email}</p><div className="row"><button disabled={busy||recording} onClick={()=>void action(async()=>{for(const row of await listRecordings())await syncMetadata(row);setNotice('Đã đồng bộ thông tin video.');})}>Đồng bộ thông tin</button><button disabled={busy||recording} onClick={()=>void action(async()=>{await(await getClient())?.auth.signOut();setDriveEmail('');location.reload();})}>Đăng xuất</button></div></section>}
      <footer>Phát triển bởi @luudhung<div><a href="/privacy" target="_blank">Quyền riêng tư</a> · <a href="/terms" target="_blank">Điều khoản</a></div></footer>
    </aside></div>}
  </main>;
}
